services:
  mongodb:
    image: mongo
    container_name: oauth2-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    networks:
      - oauth2-net

  redis:
    image: redis
    container_name: oauth2-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - oauth2-net

volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local

networks:
  oauth2-net:
    driver: bridge